### ISSUE TITLE
CNC machine specifications 

### ISSUE THREAD

**Issue by TheDiamondDirt** [kenp-io/not-for-iphone-usb-c#4]
Hey ! Do you know what drill bit you used for this project, do you have a link for it ? Do you also have feeds and speeds for it ? Thanks

**Comment by Logicenios** [comment]
Feeds and speeds get determined by the machine and the tool. If you have the same machine then it would make sense to use the same if not it would not make sense to use the same as you could destroy your phone.

**Comment by kenp-io** [comment]
To add on @Logicenios 's answer, when in doubt, go slow. I don't have a link for the drill because I was renting a CNC machine and I used the bits that were available there. I made it work with a 1mm bit, I would say it's a nice compromise because bigger doesn't quite fit and smaller might be too fragile. We're not removing a lot material, if the bit is rated for steel it should be good.
